# https://github.com/bitnami/charts/blob/main/bitnami/cassandra/values.yaml
image:
  registry: docker.io
  repository: bitnami/cassandra
  tag: 4.1.7-debian-12-r3
 
dbUser:
  user: cassandra
  forcePassword: false
  password: "7layer"


## @param initDBConfigMap ConfigMap with cql scripts. Useful for creating a keyspace and pre-populating data
##
initDBConfigMap: "otk-cassandra-schema"

resourcesPreset: "xlarge"


persistence:
  enabled: true
  size: 8Gi
