apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: gateway-instrumentation
spec:
  exporter:
    endpoint: http://localhost:4317
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"