apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/serviceaccount/serviceaccount.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-license
  files:
  - ./resources/secrets/license/license.xml
- name: gateway-secret
  env: ./resources/secrets/gateway/secret.env
- name: graphman-encryption-secret
  env: ./resources/secrets/gateway/graphman-encryption-secret.env
- name: graphman-repository-secret
  env: ./resources/secrets/repository/graphman-repository-secret.env
- name: graphman-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/cluster-property.json
- name: restman-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/cluster-property.bundle
- name: telemetry-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/telemetry.bundle
- name: service-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/service-test.bundle
# Create a secret for the Ingress Resource
# Uncomment this section to create your own certificate for the ingress controller.
# - name: gatewaytls
#   files:
#   - ./resources/secrets/tls/tls.crt
#   - ./resources/secrets/tls/tls.key
#   type: "kubernetes.io/tls"

