apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-license
  files:
  - ./resources/secrets/license/license.xml
- name: gateway-secret
  env: ./resources/secrets/gateway/secret.env
- name: graphman-encryption-secret
  env: ./resources/secrets/gateway/graphman-encryption-secret.env
- name: graphman-repository-secret
  env: ./resources/secrets/repository/graphman-repository-secret.env
- name: harbor-reg-cred
  type: kubernetes.io/dockerconfigjson
  files:
  - ./resources/secrets/registry/.dockerconfigjson
# Create a secret for the Ingress Resource
# Uncomment this section to create your own certificate for the ingress controller.
# - name: <secretName>
#   files:
#   - ../resources/secrets/tls/tls.crt
#   - ../resources/secrets/tls/tls.key
#   type: "kubernetes.io/tls"

