apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./resources/serviceaccount/serviceaccount.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: gateway-license
  files:
  - ./resources/secrets/license/license.xml
- name: gateway-secret
  env: ./resources/secrets/gateway/secret.env
- name: graphman-encryption-secret
  env: ./resources/secrets/gateway/graphman-encryption-secret.env
- name: graphman-repository-secret
  env: ./resources/secrets/repository/graphman-repository-secret.env
- name: graphman-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/cluster-property.json
- name: restman-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/cluster-property.bundle
- name: telemetry-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/telemetry.bundle
- name: service-bootstrap-bundle
  files:
    - ./resources/secrets/bundles/service-test.bundle
- name: global-bundle
  files:
    - ./resources/secrets/bundles/global-graphman-bundle.json

# Local Repository Secret
- name: local-repo-secret
  files:
    - ./resources/secrets/repository/local-repository.json

# Stored Passwords
- name: multi-ext-secret
  files:
    - dbcredentials=./resources/secrets/secrets/multi/dbcredentials.json
    - ./resources/secrets/secrets/multi/secret2
    - secret3=./resources/secrets/secrets/multi/secret3.key
- name: single-ext-secret
  files:
    - ./resources/secrets/secrets/single-secret

# Trusted Certs
- name: multi-cert-secret
  files:
    - ./resources/secrets/trustedcerts/digicert-chain.pem
    - ./resources/secrets/trustedcerts/www.broadcom.com.pem
- name: single-cert-secret
  files:
    - ./resources/secrets/trustedcerts/www.vmware.com.pem

# Create a secret for the Ingress Resource
# Uncomment this section to create your own certificate for the ingress controller.
# - name: gatewaytls
#   files:
#   - ./resources/secrets/tls/tls.crt
#   - ./resources/secrets/tls/tls.key
#   type: "kubernetes.io/tls"

