apiVersion: kuttl.dev/v1beta1
kind: TestSuite
artifactsDir: ./tests/_build/artifacts/
testDirs:
  - ./tests/e2e/
timeout: 120
crdDir: ./config/crd/bases/
namespace: l7operator
#skipDelete: true
parallel: 1
commands:
  - command: kubectl create namespace l7operator
  - command: kubectl apply -f deploy/bundle.yaml --namespace l7operator
  - command: kubectl create secret generic gateway-license --from-file=./testdata/license.xml --namespace l7operator
  - command: kubectl create secret generic test-repository-secret --from-literal=USERNAME=uppoju --from-literal=TOKEN=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 --namespace l7operator
  - command: kubectl create secret generic graphman-encryption-secret --from-literal=FRAMEWORK_ENCRYPTION_PASSPHRASE=7layer -n l7operator