apiVersion: kuttl.dev/v1beta1
kind: TestSuite
artifactsDir: ./tests/_build/artifacts/
testDirs:
  - ./tests/e2e/
timeout: 120
crdDir: ./config/crd/bases/
namespace: l7operator
#skipDelete: true
parallel: 1
commands:
  - command: kubectl create secret generic graphman-encryption-secret --from-literal=FRAMEWORK_ENCRYPTION_PASSPHRASE=7layer -n l7operator