global:
  portalRepository: caapim/
  pullSecret: broadcom-apim
  subdomainPrefix: dev-portal
  databasePassword: 7layer
  demoDatabaseRootPassword: 7layer
  demoDatabaseReplicationPassword: 7layer

portal:
  domain: brcmlabs.com
  analytics:
    enabled: false
  seaweedFs:
    enabled: false
  internalSSG:
    secretName: ssg-secret
  papi:
    secretName: papi-secret

ingress:
  class:
    name: contour
    enabled: true
  type:
    kubernetes: false
    openshift: false
    contour: true
  secretName: dispatcher-tls
  create: true
  annotations: {}
  tenantIds:
    - portal

image:
  dispatcher: dispatcher:5.4.2.2
  apim: ingress:5.4.2.2
  enterprise: portal-enterprise:5.4.2.2
  data: portal-data:5.4.2.2
  tps: tenant-provisioning-service:5.4.2.2
  analytics: analytics-server:5.4.2.2
  authenticator: authenticator:5.4.2.2
  dbUpgrade: db-upgrade-portal:5.4.2.1
  rbacUpgrade: db-upgrade-rbac:5.4.2
  upgradeVerify: upgrade-verify:5.4.2
  tlsManager: tls-automator:5.4.2

rabbitmq:
  enabled: true
  host: rabbitmq
  fullnameOverride: rabbitmq
  image:
    registry: caapim
    repository: message-broker
    tag: "5.4.2"
    pullSecrets:
      - broadcom-apim
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: ""
  serviceAccount:
    create: true
  rbac:
    create: true
  persistence:
    enabled: true
  replicaCount: 1
  clustering:
    forceBoot: false
  service:
    port: 5672
    extraPorts:
    - name: mqtt
      port: 1883
      targetPort: mqtt
  extraContainerPorts:
  - name: mqtt
    containerPort: 1883
  auth:
    username: user
    secretName: rabbitmq-secret
    existingPasswordSecret: rabbitmq-secret
    existingErlangSecret: rabbitmq-secret
    password: 7layereyal7
    erlangCookie: L7Secure
  extraPlugins: "rabbitmq_web_mqtt"
  loadDefinition:
    enabled: true
    existingSecret: rabbitmq-load-definition
  extraConfiguration: |-
    management.load_definitions = /app/load_definition.json
    mqtt.exchange = portal-external
    mqtt.subscription_ttl = 86400000
    mqtt.prefetch = 1
    disk_free_limit.absolute = 2GB
  resources:
    limits: {}
    requests: {}
  customLivenessProbe:
    exec:
      command:
        - sh
        - -ec
        - curl -f  --user {{ .Values.auth.username }}:$RABBITMQ_PASSWORD 127.0.0.1:{{ .Values.containerPorts.manager }}/api/health/checks/virtual-hosts
  customReadinessProbe:
    exec:
      command:
        - sh
        - -ec
        - curl -f  --user {{ .Values.auth.username }}:$RABBITMQ_PASSWORD 127.0.0.1:{{ .Values.containerPorts.manager }}/api/health/checks/local-alarms

mysql:
  image:
    repository: docker.io/mysql
    tag: "8.4.4"
  initdbScripts:
    elevate-admin.sql: |
      GRANT ALL PRIVILEGES ON *.* TO 'portal'@'%'; FLUSH PRIVILEGES;
  commonAnnotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"

