# permissions for end users to view gateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-viewer-role
rules:
- apiGroups:
  - security.brcmlabs.com
  resources:
  - gateways
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.brcmlabs.com
  resources:
  - gateways/status
  verbs:
  - get
