{
 "title": "Gateway Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": {
     "query": "l7_http_request_total{service_name!=\"\"}"
    }
   },
   {
    "name": "gatewayDeployment",
    "label": "Gateway Deployment",
    "query": {
     "query": "l7_http_request_total{job!=\"\"}"
    }
   },
   {
    "name": "requestMethod",
    "label": "Request Method",
    "query": {
     "query": "l7_http_request_total{request_method!=\"\"}"
    }
   },
   {
    "name": "gatewayPod",
    "label": "Pod",
    "query": {
     "query": "l7_http_request_total{pod!=\"\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Service Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(l7_http_request_total{job=\"$gatewayDeployment\"})",
     "legendFormat": "{{podName}}"
    }
   ]
  },
  {
   "title": "Successful Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(l7_total_service_success{job=\"ssg\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Routing Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l7_total_service_routing_failures{job=\"ssg\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transactions Per Second (Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(l7_http_request_total{job=\"$gatewayDeployment\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Policy Violations",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "l7_total_service_policy_violations{}",
     "legendFormat": "{{apiName}}"
    }
   ]
  },
  {
   "title": "Transactions Per Second  (Service)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(l7_http_request_total{job=\"$gatewayDeployment\",service_name!=\"\",request_method=\"$requestMethod\"}[$__rate_interval])",
     "legendFormat": "{{pod}}-{{service_name}}-{{request_method}}"
    }
   ]
  },
  {
   "title": "Avg. Latency (milliseconds)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l7_service_latency_sum{job=\"$gatewayDeployment\"} / l7_service_routing_latency_count{job=\"$gatewayDeployment\"}",
     "legendFormat": "{{pod}}-{{apiName}}"
    }
   ]
  },
  {
   "title": "Service Latency Bucket ($serviceName - $gatewayPod)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "l7_service_latency_bucket{job=\"$gatewayDeployment\",pod=\"$gatewayPod\",serviceName=\"$serviceName\"}",
     "legendFormat": "{{le}}ms"
    }
   ]
  },
  {
   "title": "Requests per service",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "l7_http_request_total{gateway_name!=\"\",service_name!=\"\"}"
    }
   ]
  },
  {
   "title": "Gateway Application Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_utilization",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "process_runtime_jvm_system_cpu_load_1m",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage{type=\"non_heap\"}",
     "legendFormat": "{{pod}}-{{pool}}-{{type}}"
    }
   ]
  },
  {
   "title": "Memory Usage (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_runtime_jvm_memory_usage{type=\"heap\"}",
     "legendFormat": "{{pod}}-{{pool}}-{{type}}"
    }
   ]
  }
 ]
}