---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-security-brcmlabs-com-v1-gateway
  failurePolicy: Fail
  name: mgateway.kb.io
  rules:
  - apiGroups:
    - security.brcmlabs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-security-brcmlabs-com-v1-repository
  failurePolicy: Fail
  name: mrepository.kb.io
  rules:
  - apiGroups:
    - security.brcmlabs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-security-brcmlabs-com-v1-gateway
  failurePolicy: Fail
  name: vgateway.kb.io
  rules:
  - apiGroups:
    - security.brcmlabs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gateways
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-security-brcmlabs-com-v1-repository
  failurePolicy: Fail
  name: vrepository.kb.io
  rules:
  - apiGroups:
    - security.brcmlabs.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
