# permissions for end users to edit l7apis.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: role
    app.kubernetes.io/instance: l7api-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: layer7-operator
    app.kubernetes.io/part-of: layer7-operator
    app.kubernetes.io/managed-by: kustomize
  name: l7api-editor-role
rules:
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7apis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7apis/status
  verbs:
  - get
