# permissions for end users to view l7statestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: layer7-operator
    app.kubernetes.io/managed-by: kustomize
  name: l7statestore-viewer-role
rules:
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7statestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7statestores/status
  verbs:
  - get
