apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
spec:
  version: 8.8.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
