apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
spec:
  version: 9.3.1
  count: 1
  elasticsearchRef:
    name: quickstart
  http:
    service:
      metadata:
        annotations:
          projectcontour.io/upstream-protocol.tls: "5601" 
      spec:
        type: ClusterIP # default is ClusterIP
