apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: ssg-prom
spec:
  image: otel/opentelemetry-collector-contrib:0.97.0
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
    exporters:
      debug:
        verbosity: basic
      prometheus:
        endpoint: "0.0.0.0:8889"
        const_labels:
          name: ssg
      otlp:
        endpoint: simple-allinone-collector:4317
        tls:
          insecure: true
    service:
      telemetry:
        logs:
          level: "debug"
        metrics:
          address: "0.0.0.0:8888"
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheus, debug]
        logs: 
          receivers: [otlp]
          exporters: [debug]
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679