apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: l7-gw-myapis
spec:
  name: l7-gw-myapis
  enabled: true
  endpoint: https://github.com/Gazza7205/l7GWMyAPIs
  branch: main
  auth:
    vendor: Github
    existingSecretName: graphman-repository-secret