apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./framework-repository.yaml
  - ./subscriptions-repository.yaml
  - ./apis-repository.yaml
  - ./local-reference-repository.yaml
  - ./otk-customizations-single.yaml
  - ../base
