apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: otk-customizations-single
spec:
  enabled: true
  endpoint: https://gitea.sutraone.com/gazza/otk-customizations-single
  branch: main
  type: git
  auth: {}
