apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: ssg
spec:
  app:
    image: docker.io/caapim/gateway:11.1.2
    management:
      cluster:
        hostname: gateway.brcmlabs.com
        password: 7layer
      password: 7layer
      username: admin
    replicas: 1
    service:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: management
        port: 9443
        protocol: TCP
        targetPort: 9443
      type: LoadBalancer
  license:
    accept: false
    secretName: gateway-license
  version: 11.1.2
status: {}
---
apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: my-repository
spec:
  auth: {}
  branch: main
  enabled: true
  endpoint: https://github.com/<username>/<repository>
  type: git
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Api
metadata:
  name: l7api-sample
spec:
  deploymentTags:
  - ssg
  - ssg1
  graphmanBundle: jsongz
  portalPublished: false
  serviceUrl: /v1/api
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  name: dev-portal
spec:
  auth: {}
  deploymentTags:
  - ssg
  enabled: true
  endpoint: dev-ssg.brcmlabs.com
  enrollmentBundle: ""
  portalTenant: portal
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7StateStore
metadata:
  name: state-store-example
spec:
  redis:
    database: 0
    groupName: l7gw
    masterPassword: 7layer
    standalone:
      host: redis-standalone
      port: 6379
    storeId: test
    type: standalone
  type: redis
