apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: ssg
spec:
  app:
    image: docker.io/caapim/gateway:10.1.00_CR3
    management:
      cluster:
        hostname: gateway.brcmlabs.com
        password: 7layer
      password: 7layer
      username: admin
    replicas: 1
    service:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: management
        port: 9443
        protocol: TCP
        targetPort: 9443
      type: LoadBalancer
  license:
    accept: false
    secretName: gateway-license
  version: 10.1.00_CR3
status: {}
---
apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: my-repository
spec:
  auth:
    token: token
    username: username
    vendor: Github
  branch: main
  enabled: true
  endpoint: https://github.com/<username>/<repository>
  name: my-repository
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Api
metadata:
  labels:
    app.kubernetes.io/created-by: layer7-operator
    app.kubernetes.io/instance: l7api-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l7api
    app.kubernetes.io/part-of: layer7-operator
  name: l7api-sample
spec: null
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  labels:
    app.kubernetes.io/created-by: layer7-operator
    app.kubernetes.io/instance: l7portal-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: l7portal
    app.kubernetes.io/part-of: layer7-operator
  name: l7portal-sample
spec:
  auth:
    clientId: cea6240880834f9e885780ae4bbb25c9
    clientSecret: db2a5aba7166492a8d9ed4fec21ec5e6
    endpoint: apim-ssg-apim-euwest-prod.layer7.saas.broadcom.com
  deploymentTags:
  - ssg
  - ssg1
  - testgateway
  enabled: true
  endpoint: apim-ssg-apim-euwest-prod.layer7.saas.broadcom.com
  enrollmentBundle: ""
  mode: auto
  name: verga
