apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: ssg
spec:
  app:
    image: docker.io/caapim/gateway:11.1.1
    management:
      cluster:
        hostname: gateway.brcmlabs.com
        password: 7layer
      password: 7layer
      username: admin
    replicas: 1
    service:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: management
        port: 9443
        protocol: TCP
        targetPort: 9443
      type: LoadBalancer
  license:
    accept: false
    secretName: gateway-license
  version: 11.1.1
status: {}
---
apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: my-repository
spec:
  auth: {}
  branch: main
  enabled: true
  endpoint: https://github.com/<username>/<repository>
  type: git
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Api
metadata:
  name: l7api-sample
spec:
  deploymentTags:
  - ssg
  - ssg1
  graphmanBundle: jsongz
  portalPublished: false
  serviceUrl: /v1/api
---
apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  name: dev-portal
spec:
  auth:
    clientId: 3d8f8967b8e54909b5e9a86e09063406
    clientSecret: b40a829f046a451db15aa8be503ea7b3
    endpoint: dev-ssg.brcmlabs.com
  deploymentTags:
  - ssg
  enabled: true
  endpoint: dev-ssg.brcmlabs.com
  enrollmentBundle: ""
  portalTenant: portal
