apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: ssg
spec:
  app:
    image: docker.io/caapim/gateway:10.1.00_CR3
    management:
      cluster:
        hostname: gateway.brcmlabs.com
        password: 7layer
      password: 7layer
      username: admin
    replicas: 1
    service:
      ports:
      - name: https
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: management
        port: 9443
        protocol: TCP
        targetPort: 9443
      type: LoadBalancer
  license:
    accept: false
    secretName: gateway-license
  version: 10.1.00_CR3
status: {}
---
apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: my-repository
spec:
  auth:
    token: token
    username: username
    vendor: Github
  branch: main
  enabled: true
  endpoint: https://github.com/<username>/<repository>
  name: my-repository
