
image:
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.4.3-debian-12-r5
  pullPolicy: IfNotPresent
auth:
  username: otk_user
  password: 7layer
  database: otk_db
  rootPassword: 7layer
primary:
  persistence:
    enabled: true
    size: 8Gi
  configuration: |-
    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/plugin
    [mysqld]
    log-bin-trust-function-creators=1
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    collation-server=utf8_general_ci
    character-set-server=UTF8
    innodb_log_buffer_size=64M
    innodb_log_file_size=80M
    max_allowed_packet=20M
    sql_mode = "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    bind-address=0.0.0.0
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    [manager]
    port=3306
