{
 "title": "Layer7 Operator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "operatorNamespace",
    "label": "Namespace",
    "query": {
     "query": "layer7_operator_gw_external_references{}"
    }
   },
   {
    "name": "operatorPod",
    "label": "Pod",
    "query": {
     "query": "layer7_operator_gw_external_references{k8s_namespace_name=\"$operatorNamespace\"}"
    }
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "layer7_operator_gw_external_references{k8s_pod_name=\"$operatorPod\"}"
    }
   },
   {
    "name": "gatewayNamespace",
    "label": "Gateway Namespace",
    "query": {
     "query": "layer7_operator_gw_external_references{k8s_pod_name=\"$operatorPod\",gateway_name=\"$gateway\"}"
    }
   },
   {
    "name": "repositoryNamespace",
    "label": "Repository Namespace",
    "query": {
     "query": "layer7_operator_repository_sync_total{k8s_pod_name=\"$operatorPod\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Layer7 Operator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Repository References",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_external_references{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Key References",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_external_references{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Secret References",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_external_references{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Controller Reconcile Histogram",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "layer7_operator_gw_reconciler_latency_milliseconds_bucket{k8s_pod_name=\"$operatorPod\",k8s_namespace_name=\"$operatorNamespace\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Gateway Controller Reconcile Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_reconcile_total{k8s_pod_name=\"$operatorPod\",gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Controller Reconcile Failure",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_reconcile_failure_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Controller Reconcile Success",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_gw_reconcile_success_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{pod=\"$operatorPod\", k8s_namespace_name=\"$operatorNamespace\", container=\"manager\"} |= ``"
    }
   ]
  },
  {
   "title": "Repository Controller Reconcile Histogram",
   "type": "histogram",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 11 },
   "targets": [
    {
     "expr": "layer7_operator_repo_reconciler_latency_milliseconds_bucket{k8s_pod_name=\"$operatorPod\",k8s_namespace_name=\"$operatorNamespace\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Graphman Requests - $gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "gateway" },
  {
   "title": "Total Graphman Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "layer7_operator_graphman_request_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\", gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Failed Graphman Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(layer7_operator_graphman_request_failure_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\", gateway_namespace=\"$gatewayNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Graphman Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(layer7_operator_graphman_request_success_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\", gateway_namespace=\"$gatewayNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(layer7_operator_graphman_latency_milliseconds_sum{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\",gateway_namespace=\"$gatewayNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graphman Request Latency Histogram",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(layer7_operator_graphman_latency_milliseconds_bucket{gateway_name=\"$gateway\", k8s_pod_name=\"$operatorPod\", gateway_namespace=\"$gatewayNamespace\"}[$__rate_interval])) by (le))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Successful Graphman Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "layer7_operator_graphman_request_success_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\", gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Graphman Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "layer7_operator_graphman_request_failure_total{k8s_pod_name=\"$operatorPod\", gateway_name=\"$gateway\", gateway_namespace=\"$gatewayNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Repository Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Repository Sync Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(layer7_operator_repository_sync_total{k8s_pod_name=\"$operatorPod\", repository_namespace=\"$repositoryNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Sync Failure",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(layer7_operator_repository_sync_failure_total{k8s_pod_name=\"$operatorPod\", repository_namespace=\"$repositoryNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Sync Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(layer7_operator_repository_sync_success_total{k8s_pod_name=\"$operatorPod\", repository_namespace=\"$repositoryNamespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Sync Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 40 },
   "targets": [
    {
     "expr": "layer7_operator_repository_sync_latency_milliseconds_bucket{k8s_pod_name=\"$operatorPod\", k8s_namespace_name=\"$operatorNamespace\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Successful Repository Syncs",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "layer7_operator_repository_sync_success_total{k8s_namespace_name=\"$operatorNamespace\", k8s_pod_name=\"$operatorPod\", repository_namespace=\"$repositoryNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Repository Syncs",
   "type": "table",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 47 },
   "targets": [
    {
     "expr": "layer7_operator_repository_sync_failure_total{k8s_namespace_name=\"$operatorNamespace\", k8s_pod_name=\"$operatorPod\", repository_namespace=\"$repositoryNamespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}