apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Api
metadata:
  name: l7api-sample
spec:
  portalPublished: false
  graphmanBundle: jsongz
  serviceUrl: /v1/api
  deploymentTags:
  - ssg
  - ssg1

