apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  name: dev-portal
spec:
  portalTenant: portal
  enabled: true
  endpoint: dev-ssg.brcmlabs.com
  mode: auto
  enrollmentBundle: ""
  deploymentTags:
  - ssg
  auth:
    endpoint: dev-ssg.brcmlabs.com
    clientId: 3d8f8967b8e54909b5e9a86e09063406
    clientSecret: b40a829f046a451db15aa8be503ea7b3