apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  labels:
    app.kubernetes.io/name: l7portal
    app.kubernetes.io/instance: l7portal-sample
    app.kubernetes.io/part-of: layer7-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: layer7-operator
  name: l7portal-sample
spec:
  name: verga
  enabled: true
  endpoint: apim-ssg-apim-euwest-prod.layer7.saas.broadcom.com
  mode: auto
  enrollmentBundle: ""
  deploymentTags:
  - ssg
  - ssg1
  - testgateway
  auth:
    endpoint: apim-ssg-apim-euwest-prod.layer7.saas.broadcom.com
    clientId: cea6240880834f9e885780ae4bbb25c9
    clientSecret: db2a5aba7166492a8d9ed4fec21ec5e6
