apiVersion: security.brcmlabs.com/v1alpha1
kind: L7Portal
metadata:
  name: dev-portal
spec:
  portalTenant: portal
  enabled: true
  endpoint: dev-ssg.brcmlabs.com
  enrollmentBundle: ""
  deploymentTags:
  - ssg
  auth: {}