apiVersion: security.brcmlabs.com/v1alpha1
kind: L7StateStore
metadata:
  name: state-store-example
spec:
  type: redis
  redis:
    database: 0
    groupName: l7gw
    type: standalone
    masterPassword: 7layer
    standalone:
      host: redis-standalone
      port: 6379
    storeId: test
