apiVersion: security.brcmlabs.com/v1alpha1
kind: L7StateStore
metadata:
  name: portal-state-store
spec:
  type: redis
  redis:
    database: 0
    groupName: portal-store
    type: standalone
    masterPassword: 7layer
    standalone:
      host: standalone-redis-master
      port: 6379
    storeId: test
   