# Adds namespace to all resources.
#namespace: layer7-operator-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: layer7-operator-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
- ../crd
- ../rbac
- ../operator
- ./metrics_service.yaml

images:
- name: controller
  newName: docker.io/layer7api/layer7-operator
  newTag: main


patches:
- path: manager_metrics_patch.yaml
  target:
    kind: Deployment

