apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portal-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portal-role
subjects:
- kind: ServiceAccount
  name: portal-sa
