apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "layer7-operator.fullname" . }}-controller-manager
  labels:
  {{- include "layer7-operator.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.commonLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{- range $key, $val := .Values.commonAnnotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
data:
  {{- if ne (include "layer7-operator.managedNamespaces" .) "" }}
  WATCH_NAMESPACE: {{ template "layer7-operator.managedNamespaces" . }}
  {{- else }}
  WATCH_NAMESPACE: ""
  {{- end }}
  ENABLE_WEBHOOK: {{ .Values.webhook.enabled | quote }}
  HTTP_PROXY: {{ .Values.proxy.httpProxy | quote }}
  HTTPS_PROXY: {{ .Values.proxy.httpsProxy | quote }}
  NO_PROXY: {{ .Values.proxy.noProxy | quote }}
  KUBERNETES_CLUSTER_DOMAIN: {{ .Values.clusterDomain | quote }}