apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "layer7-operator.fullname" . }}-l7statestore-viewer-role
  labels:
  {{- include "layer7-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7statestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - security.brcmlabs.com
  resources:
  - l7statestores/status
  verbs:
  - get