apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "layer7-operator.fullname" . }}-manager-config
  labels:
    {{- include "layer7-operator.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.commonLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{- range $key, $val := .Values.commonAnnotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
data:
  controller_manager_config.yaml: |+
    apiVersion: controller-runtime.sigs.k8s.io/v1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: d464e6a2.brcmlabs.com