apiVersion: v1
kind: Service
metadata:
  name: {{ include "layer7-operator.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "layer7-operator.labels" . | nindent 4 }}
    {{- range $key, $val := .Values.commonLabels }}
    {{ $key }}: "{{ $val }}"
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{- range $key, $val := .Values.commonAnnotations }}
   {{ $key }}: "{{ $val }}"
{{- end }}
{{- end }}
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  {{- include "layer7-operator.selectorLabels" . | nindent 4 }}
  ports:
  - name: https
    port: 8443
    targetPort: https