apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "layer7-operator.fullname" . }}-controller-manager
  labels:
  {{- include "layer7-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}