apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: portal-ssg
spec:
  version: "11.0.00_CR2"
  license:
    accept: false
    secretName: gateway-license
  app:
    replicas: 1
    image: caapim/gateway:11.0.00_CR2
    imagePullPolicy: IfNotPresent
    updateStrategy:
      type: rollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    resources:
      requests:
        memory: 4Gi
        cpu: 2
      limits:
        memory: 4Gi
        cpu: 2
    autoscaling:
      enabled: false
    redis:
      enabled: true
      type: standalone
      standalone:
        hostname: standalone-redis-master.redis.svc.cluster.local
        port: 6379
    bundle: []
    repositoryReferences: []
    portalReference:
      enabled: false
      portalName: dev-portal
      initContainerImagePullPolicy: Always
    bootstrap:
      script:
        enabled: true
    initContainers:
    - name: gateway-init
      image: layer7api/gateway-portal-init:1.0.0
      imagePullPolicy: Always
      volumeMounts:
      - name: config-directory
        mountPath: /opt/docker/custom
    management:
      secretName: gateway-secret
      service:
        enabled: false
      restman:
        enabled: false
      graphman:
        enabled: true
        initContainerImage: docker.io/layer7api/graphman-static-init:1.0.1
      cluster:
        hostname: gateway.brcmlabs.com
      database:
        enabled: false
    java:
      jvmHeap:
        calculate: true
        percentage: 75
        default: 4g
      extraArgs:
      - -Dcom.l7tech.server.audit.message.saveToInternal=false
      - -Dcom.l7tech.server.audit.admin.saveToInternal=false
      - -Dcom.l7tech.server.audit.system.saveToInternal=false
      - -Dcom.l7tech.server.audit.log.format=json
      - -Djava.util.logging.config.file=/opt/SecureSpan/Gateway/node/default/etc/conf/log-override.properties
      - -Dcom.l7tech.security.ssl.hostAllowWildcard=true
      - -Dcom.l7tech.server.pkix.useDefaultTrustAnchors=true
      - -Dcom.l7tech.bootstrap.autoTrustSslKey=trustAnchor,TrustedFor.SSL,TrustedFor.SAML_ISSUER
    listenPorts:
      harden: false
      custom:
        enabled: false
      ports: []
    cwp:
      enabled: true
      properties:
        - name: io.httpsHostAllowWildcard
          value: "true"
        - name: log.levels
          value: |
            com.l7tech.level = CONFIG
            com.l7tech.server.policy.variable.ServerVariables.level = SEVERE
            com.l7tech.external.assertions.odata.server.producer.jdbc.GenerateSqlQuery.level = SEVERE
            com.l7tech.server.policy.assertion.ServerSetVariableAssertion.level = SEVERE
            com.l7tech.external.assertions.comparison.server.ServerComparisonAssertion = SEVERE
        - name: audit.setDetailLevel.FINE
          value: 152 7101 7103 9648 9645 7026 7027 4155 150 4716 4114 6306 4100 9655 150 151 11000 4104
    system:
      properties: |-
        # Default Gateway system properties
        # Configuration properties for shared state extensions.
        # com.l7tech.server.extension.sharedKeyValueStoreProvider=redis
        # com.l7tech.server.extension.sharedCounterProvider=ssgdb
        com.l7tech.server.extension.sharedRateLimiterProvider=ssgdb
        com.l7tech.server.extension.sharedClusterInfoProvider=ssgdb
        # By default, FIPS module will block an RSA modulus from being used for encryption if it has been used for
        # signing, or visa-versa. Set true to disable this default behaviour and remain backwards compatible.
        com.safelogic.cryptocomply.rsa.allow_multi_use=true
        # Specifies the type of Trust Store (JKS/PKCS12) provided by AdoptOpenJDK that is used by Gateway.
        # Must be set correctly when Gateway is running in FIPS mode. If not specified it will default to PKCS12.
        javax.net.ssl.trustStoreType=jks
        com.l7tech.server.clusterStaleNodeCleanupTimeoutSeconds=86400
        # Additional properties go here
        org.apache.xml.security.ignoreLineBreaks=true
        # Redis configuration - uncomment to use Redis
        com.l7tech.server.extension.sharedKeyValueStoreProvider=redis
        com.l7tech.server.extension.sharedCounterProvider=redis
        com.l7tech.server.extension.sharedRateLimiterProvider=redis
    service:
      # annotations:
      type: ClusterIP
      ports:
      - name: https
        port: 8443
        targetPort: 8443
        protocol: TCP
      - name: management
        port: 9443
        targetPort: 9443
        protocol: TCP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls:
      - hosts: 
        - gateway.brcmlabs.com
        secretName: brcmlabs
      rules:
      - host: gateway.brcmlabs.com