apiVersion: security.brcmlabs.com/v1
kind: Gateway
metadata:
  name: portal-ssg
spec:
  version: "11.1.1"
  license:
    accept: true
    secretName: gateway-license
  app:
    replicas: 1
    image: caapim/gateway:11.1.1
    imagePullPolicy: IfNotPresent
    updateStrategy:
      type: rollingUpdate
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
    resources:
      requests:
        memory: 4Gi
        cpu: 2
      limits:
        memory: 4Gi
        cpu: 2
    autoscaling:
      enabled: false
      hpa:
        minReplicas: 2
        maxReplicas: 3
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 60
        behavior:
          scaleDown:
            stabilizationWindowSeconds: 300
            policies:
            - type: Pods
              value: 1
              periodSeconds: 60
          scaleUp:
            stabilizationWindowSeconds: 0
            policies:
            - type: Percent
              value: 100
              periodSeconds: 15
    redis:
      enabled: false
      default:
        auth:
          enabled: false
          username: admin
          passwordPlaintext: password!£$^%^!!!
          #passwordEncoded: esfksepofksepofksopef12312po3%$(%$($))
        type: standalone
        standalone:
          host: standalone-redis-master
          port: 6379
        ssl:
          enabled: false
          existingSecretName: redis-ssl-cert
          existingSecretKey: redis.crt
          verifyPeer: true
    bundle: []
    repositoryReferences:
      - name: local-reference-repository
        enabled: false
        type: dynamic
        encryption:
          existingSecret: graphman-encryption-secret
          key: APIS_ENCRYPTION_PASSPHRASE
      - name: oom-repo
        enabled: false
        type: dynamic
        encryption:
          passphrase: mydemo123
          # existingSecret: graphman-encryption-secret
          # key: APIS_ENCRYPTION_PASSPHRASE
    portalReference:
      enabled: false
      portalName: dev-portal
      initContainerImagePullPolicy: Always
    bootstrap:
      script:
        enabled: true
    initContainers:
    - name: gateway-init
      image: harbor.sutraone.com/operator/gateway-portal-init:1.0.1
      imagePullPolicy: Always
      volumeMounts:
      - name: config-directory
        mountPath: /opt/docker/custom
    management:
      secretName: gateway-secret
      service:
        enabled: false
      restman:
        enabled: false
      graphman:
        enabled: true
        initContainerImage: docker.io/caapim/graphman-static-init:1.0.2
      cluster:
        hostname: gateway.brcmlabs.com
      database:
        enabled: false
    java:
      jvmHeap:
        calculate: true
        percentage: 75
        default: 4g
      extraArgs:
      - -Dcom.l7tech.server.audit.message.saveToInternal=false
      - -Dcom.l7tech.server.audit.admin.saveToInternal=false
      - -Dcom.l7tech.server.audit.system.saveToInternal=false
      - -Dcom.l7tech.server.audit.log.format=json
      - -Djava.util.logging.config.file=/opt/SecureSpan/Gateway/node/default/etc/conf/log-override.properties
      - -Dcom.l7tech.security.ssl.hostAllowWildcard=true
      - -Dcom.l7tech.server.pkix.useDefaultTrustAnchors=true
      - -Dcom.l7tech.bootstrap.autoTrustSslKey=trustAnchor,TrustedFor.SSL,TrustedFor.SAML_ISSUER
    listenPorts:
      harden: true
      refreshOnKeyChanges: false
      custom:
        enabled: false
      ports: []
    cwp:
      enabled: true
      properties:
        - name: kevintest
          value: kevinvalue123
        - name: cwptest
          value: myclusterprop123
        - name: io.httpsHostAllowWildcard
          value: "true"
        - name: log.levels
          value: |
            com.l7tech.level = CONFIG
            com.l7tech.server.policy.variable.ServerVariables.level = SEVERE
            com.l7tech.external.assertions.odata.server.producer.jdbc.GenerateSqlQuery.level = SEVERE
            com.l7tech.server.policy.assertion.ServerSetVariableAssertion.level = SEVERE
            com.l7tech.external.assertions.comparison.server.ServerComparisonAssertion = SEVERE
        - name: audit.setDetailLevel.FINE
          value: 152 7101 7103 9648 9645 7026 7027 4155 150 4716 4114 6306 4100 9655 150 151 11000 4104
    system:
      properties: |-
        # Default Gateway system properties
        # Configuration properties for shared state extensions.
        # com.l7tech.server.extension.sharedKeyValueStoreProvider=redis
        # com.l7tech.server.extension.sharedCounterProvider=ssgdb
        com.l7tech.server.extension.sharedRateLimiterProvider=ssgdb
        com.l7tech.server.extension.sharedClusterInfoProvider=ssgdb
        # By default, FIPS module will block an RSA modulus from being used for encryption if it has been used for
        # signing, or visa-versa. Set true to disable this default behaviour and remain backwards compatible.
        com.safelogic.cryptocomply.rsa.allow_multi_use=true
        # Specifies the type of Trust Store (JKS/PKCS12) provided by AdoptOpenJDK that is used by Gateway.
        # Must be set correctly when Gateway is running in FIPS mode. If not specified it will default to PKCS12.
        javax.net.ssl.trustStoreType=jks
        com.l7tech.server.clusterStaleNodeCleanupTimeoutSeconds=86400
        # Additional properties go here
        org.apache.xml.security.ignoreLineBreaks=true
        # Redis configuration - uncomment to use Redis
        # com.l7tech.server.extension.sharedKeyValueStoreProvider=redis
        # com.l7tech.server.extension.sharedCounterProvider=redis
        # com.l7tech.server.extension.sharedRateLimiterProvider=redis
        # com.l7tech.external.assertions.keyvaluestore.sharedKeyValueStoreProvider=redis
        # com.l7tech.external.assertions.keyvaluestore.storeIdList=GW_STORE_ID
        # com.l7tech.external.assertions.keyvaluestore.storeIdPrefix=""
    service:
      # annotations:
      type: ClusterIP
      ports:
      - name: https
        port: 8443
        targetPort: 8443
        protocol: TCP
      - name: management
        port: 9443
        targetPort: 9443
        protocol: TCP
    ingress:
      enabled: false
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      tls:
      - hosts: 
        - gateway.brcmlabs.com
        secretName: brcmlabs
      rules:
      - host: gateway.brcmlabs.com