apiVersion: security.brcmlabs.com/v1
kind: Repository
metadata:
  name: l7-gw-myapis
spec:
  enabled: true
  endpoint: ssh://git@[yourgitserver.com]/[username]/[reponame]
  #endpoint: ssh://git@[yourgitserver.com]:[port]/[username]/[reponame]
  branch: main
  type: git
  auth:
    type: ssh
    existingSecretName: myapis-sshkey