apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./apis-repository.yaml
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: myapis-sshkey
  files: 
  #- SSH_KEY=./ssh_key_plaintext.key
  - SSH_KEY=./ssh_key_encrypted.key
  - KNOWN_HOSTS=./known_hosts
  - SSH_KEY_PASS=./sshpass.txt