# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/layer7-operator.clusterserviceversion.yaml
- ../cw-bundle
- ../samples
- ../scorecard

# [WEBHOOK] To enable webhooks, uncomment all the sections with [WEBHOOK] prefix.
# Do NOT uncomment sections with prefix [CERTMANAGER], as OLM does not support cert-manager.
# These patches remove the unnecessary "cert" volume and its manager container volumeMount.
patchesJson6902:
- target:
   group: apps
   version: v1
   kind: Deployment
   name: controller-manager
   namespace: system
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/volumeMounts/0
    - op: remove
      path: /spec/template/spec/volumes/0
# - target:
#     group: admissionregistration.k8s.io
#     version: v1
#     kind: MutatingWebhookConfiguration
#     name: mutatingwebhookconfiguration
#   patch: |-
#     - op: remove
#       path: /metadata/annotations
# - target:
#     group: admissionregistration.k8s.io
#     version: v1
#     kind: ValidatingWebhookConfiguration
#     name: validatingwebhookconfiguration
#   patch: |-
#     - op: remove
#       path: /metadata/annotations
   
