apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./service-account.yaml
  - ./role.yaml
  - ./rolebinding.yaml
  - ./deployment.yaml
generatorOptions:
 disableNameSuffixHash: true
configMapGenerator:
  - name: g2c-agent-configmap
    env: ./agent.env