apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portal-g2c-agent-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: portal-g2c-agent-role
subjects:
- kind: ServiceAccount
  name: portal-g2c-agent
