name: "End-to-end tests"
on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches:
      - main
      - develop
      - experimental
      - develop_l7operator
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # The e2e tests are run on the lowest and highest supported k8s version.
        # All Kubernetes version in between expose the same APIs, hence the operator
        # should be compatible with them.
        kube-version:
          - "1.31"
        group:
          - e2e
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.23.3"
      - name: Setup kind
        env:
          KIND_VERSION: "0.25.0"
        run: go install sigs.k8s.io/kind@v${KIND_VERSION}
      - name: "install kuttl"
        run: ./hack/install-kuttl.sh
      - name: "create license"
        env:
          LICENSE: ${{ secrets.GATEWAY_LICENSE }}
        run: 'echo "$LICENSE" > ./testdata/license.xml'
        shell: bash
      - name: "run tests"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
        run: | 
           make prepare-e2e ${{ matrix.group }} KUBE_VERSION=$KUBE_VERSION VERSION=${GITHUB_HEAD_REF}
           rm ./testdata/license.xml
  e2e-tests-check:
    runs-on: ubuntu-22.04
    if: always()
    needs: [e2e-tests]
    steps:
      - name: Print result
        run: echo ${{ needs.e2e-tests.result }}
      - name: Interpret result
        run: |
          if [[ success == ${{ needs.e2e-tests.result }} ]]
          then
            echo "All matrix jobs passed!"
          else
            echo "One or more matrix jobs failed."
            false
          fi