name: "Integration and Unit tests"
on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main
      - develop
      - experimental
      - develop_l7operator
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  integration-tests:
    name: integration tests
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # The e2e tests are run on the lowest and highest supported k8s version.
        # All Kubernetes version in between expose the same APIs, hence the operator
        # should be compatible with them.
        kube-version:
          - "1.28"
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "~1.21.3"
      - name: Setup kind
        env:
          KIND_VERSION: "0.20.0"
        run: go install sigs.k8s.io/kind@v${KIND_VERSION}
      - name: "create license"
        env:
          LICENSE: ${{ secrets.GATEWAY_LICENSE }}
        run: 'echo "$LICENSE" > ./testdata/license.xml'
        shell: bash
      - name: "run tests"
        env:
          KUBE_VERSION: ${{ matrix.kube-version }}
          TESTREPO_USER: ${{ secrets.TESTREPO_USER }}
          TESTREPO_TOKEN: ${{ secrets.TESTREPO_TOKEN }}
        run: |
           make test KUBE_VERSION=$KUBE_VERSION VERSION=${GITHUB_HEAD_REF}
           rm ./testdata/license.xml
  integration-tests-check:
    runs-on: ubuntu-22.04
    if: always()
    needs: [integration-tests]
    steps:
      - name: Print result
        run: echo ${{ needs.integration-tests.result }}
      - name: Interpret result
        run: |
          if [[ success == ${{ needs.integration-tests.result }} ]]
          then
            echo "All matrix jobs passed!"
          else
            echo "One or more matrix jobs failed."
            false
          fi