name: Build PR Images
on: 
  pull_request:
    branches:
      - main
      - develop
      - experimental
jobs:
  build-and-push-images:
    name: Build and Push Images
    runs-on: ubuntu-latest
    env:
      VERSION: ${GITHUB_HEAD_REF}
      IMAGE_TAG_BASE: docker.io/layer7api/layer7-operator
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Operator
        run: make docker-build docker-push
      - name: Build and push Operator Bundle
        run: make bundle-build bundle-push