name: Create Release
on: 
  push:
    tags:
      - "v*.*.*"
jobs:
  create-release:
    name: Build Deployment Manifests
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
      IMAGE_TAG_BASE: docker.io/caapim/layer7-operator
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Prepare Bases
        run: make version
      - name: Generate Deployment Manifests
        run: make generate-deployment generate-cw-deployment
      - name: Generate Deployment Bundle
        run: make generate-deployment-bundle generate-cw-deployment-bundle
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            deploy/bundle.yaml
            deploy/cw-bundle.yaml
